
import { GoogleGenAI, Modality, Type } from "@google/genai";

// Assume process.env.API_KEY is available
if (!process.env.API_KEY) {
  // This is a placeholder for development. In a real environment, the key would be set.
  console.warn("API_KEY environment variable not set. Using a placeholder.");
  // In a real deployed app, you'd want to handle this more gracefully.
}

const ai = new GoogleGenAI({ apiKey: process.env.API_KEY! });

export const generateText = async (prompt: string): Promise<string> => {
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-pro', // Using a powerful model for script writing
            contents: prompt,
        });
        return response.text;
    } catch (error) {
        console.error("Error generating text with Gemini:", error);
        throw error;
    }
};

export const generateStructuredText = async (prompt: string, schema: any): Promise<any> => {
    try {
        const response = await ai.models.generateContent({
            model: 'gemini-2.5-pro',
            contents: prompt,
            config: {
                responseMimeType: "application/json",
                responseSchema: schema,
            },
        });
        const jsonText = response.text.trim();
        return JSON.parse(jsonText);
    } catch (error) {
        console.error("Error generating structured text with Gemini:", error);
        if (error instanceof SyntaxError) {
             console.error("Failed to parse JSON response from Gemini.");
        }
        throw error;
    }
};

export const generateImage = async (prompt: string, aspectRatio: string = '1:1'): Promise<string> => {
  try {
    const response = await ai.models.generateImages({
        model: 'imagen-4.0-generate-001', // Using a high-quality model
        prompt: prompt,
        config: {
          numberOfImages: 1,
          outputMimeType: 'image/png', // Use PNG for comic panels
          aspectRatio: aspectRatio, // Panels are square
        },
    });

    if (response.generatedImages && response.generatedImages.length > 0) {
      const base64ImageBytes = response.generatedImages[0].image.imageBytes;
      return `data:image/png;base64,${base64ImageBytes}`;
    } else {
      throw new Error("No images were generated by the API.");
    }
  } catch (error) {
    console.error("Error generating image with Gemini:", error);
    // Re-throw the error to be handled by the calling component
    throw error;
  }
};

export const editImage = async (base64ImageData: string, prompt: string): Promise<string> => {
  try {
    const data = base64ImageData.split(',')[1];
    const mimeType = base64ImageData.match(/data:(image\/[a-zA-Z]+);base64,/)?.[1] || 'image/png';

    const response = await ai.models.generateContent({
        model: 'gemini-2.5-flash-image',
        contents: {
            parts: [
                {
                    inlineData: {
                        data,
                        mimeType,
                    },
                },
                { text: prompt },
            ],
        },
        config: {
            responseModalities: [Modality.IMAGE],
        },
    });
    
    for (const part of response.candidates?.[0]?.content?.parts || []) {
        if (part.inlineData) {
            return `data:${part.inlineData.mimeType};base64,${part.inlineData.data}`;
        }
    }
    
    throw new Error("No edited image was returned from the API.");

  } catch (error) {
    console.error("Error editing image with Gemini:", error);
    throw error;
  }
};